version: "3"

services:
  nginx:
    container_name: nginx-server
    build:
      context: ../nginx
      dockerfile: ../nginx/Dockerfile
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ws-server
      - xkrajn05
      - xstud00
  ws-server:
    container_name: ws-server
    build:
      context: ../server
      dockerfile: ../server/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  xkrajn05:
    container_name: xkrajn05
    build:
      context: ../q-sort-app
      dockerfile: ../q-sort-app/Dockerfile
    expose:
      - "8080"
  xstud00:
    container_name: xstud00
    build:
      context: ../test-app
      dockerfile: ../test-app/Dockerfile
    expose:
      - "8080"
