version: "3"

services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-frontend
  #   tty: true
  #   container_name: Ubuntu-Vue3-Q-sort-frontend
  #   user: root
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - type: bind
  #       source: ../q-sort-app
  #       target: /frontend-q-sort
  nginx:
    container_name: nginx-server
    build:
      context: ../nginx
      dockerfile: ../nginx/dockerfile-nginx
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ws-server
      - xkrajn05
  ws-server:
    container_name: ws-server
    build:
      context: ../server
      dockerfile: ../server/dockerfile-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  xkrajn05:
    container_name: xkrajn05
    build:
      context: ../q-sort-app
      dockerfile: ../q-sort-app/Dockerfile
    expose:
      - "8080"
  mongo:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
