version: "3"

services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-frontend
  #   tty: true
  #   container_name: Ubuntu-Vue3-Q-sort-frontend
  #   user: root
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - type: bind
  #       source: ../q-sort-app
  #       target: /frontend-q-sort
  nginx:
    build:
      context: ./docker
      dockerfile: dockerfile-nginx
    container_name: nginx-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ws-server
      - q-app
  ws-server:
    build:
      context: ./docker
      dockerfile: ./server/dockerfile-backend
    container_name: ws-server
    ports:
      - "3000:3000"
  q-app:
    build:
      context: ./docker
      dockerfile: ./q-sort-app/dockerfile-xkrajn05
    expose:
      - "8080"
