FROM ubuntu:22.04

USER root

RUN apt-get update
RUN apt-get -y install curl
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash 
RUN apt -y install nodejs
RUN npm install npm -g npm@latest
SHELL ["/bin/bash", "--login", "-i", "-c"]
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
RUN source /root/.bashrc && nvm install v18.12.0
SHELL ["/bin/bash", "--login", "-c"]

WORKDIR /frontend-q-sort
# RUN npm install
